#! /bin/bash

./onnxruntime/build.sh \
        --use_cuda \
        --cuda_home /usr/local/cuda \
        --cudnn_home /usr/lib/aarch64-linux-gnu \
        --use_tensorrt \
        --tensorrt_home /usr/lib/aarch64-linux-gnu \
        --config RelWithDebInfo \
        --build_shared_lib \
        --build \
        --build_wheel \
        --update \
        --skip_submodule_sync \
        --skip_tests \
        --arm64 \
        --cmake_extra_defines ONNXRUNTIME_VERSION=1.9.1 CMAKE_INSTALL_PREFIX=~/code/ZeroShotRT/onnxruntime/install CUDA_CMAKE_COMPILE=/usr/local/cuda/nvcc